name: Release
on:
  push:
    branches: [ main ]

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm i
      - run: bun run test
      - run: bun run build
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
          registry: 'https://npm.pkg.github.com'
